i18n.Sample/Models/HomeModels.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace i18n.Sample.Models
{
    public class HomeModel
    {
		//[Display(Name="Nombre")]
		[DisplayName("Nombre")]
		//[MaxLength(5, ErrorMessage="Este es un error sin traducir")]
		[StringLength(5, ErrorMessage="Este es un error sin traducir")]
        public string Name { get; set; }

		[Required(ErrorMessage = "Este es un error sin traducir")]
        public string CampoRequerido { get; set; }

		[Required]
		public string ErrorDefault { get; set; }
    }
}

i18n.Sample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using i18n.Sample.Models;

namespace i18n.Sample.Controllers
{
	public partial class HomeController : LocalizableController
	{
		[HttpGet]
		public virtual ActionResult Index()
		{
			var a = _("Esto es otra cadena"
				+ " multilinea");

			var b = _(@"Y esta usa una
                  arroba");

			return View();
		}

		[HttpPost]
		public virtual ActionResult Index(HomeModel model)
		{
			return View(model);
		}

	}
}

i18n.Sample/Controllers/LocalizationController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace i18n.Sample.Controllers
{
    public partial class LocalizationController : LocalizableController
    {
        #region Methods

        public virtual ActionResult Help(int? id)
        {
            return View();
        }

        public virtual ContentResult Index(string lang = "en", params string[] includes)
        {
			//You might need to pick the correct domain from config i.e. AppConfig.WebsiteDomain or ConfigurationManager.AppSettings["WebsiteDomain"]
			var domain = this.ControllerContext.HttpContext.Request.Url.DnsSafeHost;


            SwitchCulture(lang);
            var culture = CultureInfo.CurrentCulture;
            var lcid = culture.LCID;
            var sb = new StringBuilder();
            LocalizationAppConfig.LocalizationLoadComments = true;
            sb.AppendLine("var appConfig = appConfig || {};");
            sb.Append("appConfig.domain = ").Append(domain.js()).AppendLine(";");
            sb.Append("appConfig.testBaseUrl = ").Append(this.ControllerContext.HttpContext.Server.MapPath("~/app").js()).AppendLine(";");
            sb.Append("appConfig.lang = ").Append(lang.js()).AppendLine(";");
            sb.Append("appConfig.ssl = ").Append(FormsAuthentication.RequireSSL ? "true" : "false").AppendLine(";");
            sb.Append("appConfig.userInfoUrl = ").Append(Url.ActionA("Info", "User", "Account").js()).AppendLine(";");

            sb.AppendLine("appConfig.messages = {");
            foreach (var msg in I18NComplete.Localizations[lcid].Messages.Values)
                if (includes == null || includes.Length == 0 || msg.Contexts.Any(c => includes.Any(i => c.IndexOf(i, StringComparison.OrdinalIgnoreCase) >= 0)))
                {
                    sb.Append("\t").Append(msg.MsgID.js()).Append(": {");

                    if (msg.Translated || msg.HasPlural)
                    {
                        if (msg.HasPlural)
                            sb.AppendLine()
                                .Append("\t\tt: ")
                                .Append(msg.MsgStr.js())
                                .AppendLine(",")
                                .Append("\t\tp: ")
                                .Append(msg.MsgID_Plural.js())
                                .AppendLine(",")
                                .Append("\t\tpt:")
                                .Append(msg.MsgStr_Plural.js())
                                .AppendLine(",")
                                .AppendLine("\t");
                        else sb.Append("t:").Append(msg.MsgStr.js());
                    }
                    sb.AppendLine("},");
                }
            sb.AppendLine("}");

            return Content(sb.ToString(), "text/javascript");
        }

        internal static void SwitchCulture(string cultureName)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(cultureName);
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(cultureName);
        }

        #endregion Methods of LocalizationController (3)
    }
}

i18n.Sample/Views/Home/Index.cshtml
@{
    ViewBag.Title = _("Index");
}

<h2>@_("Indice")</h2>

@_("Esto es un texto de prueba, para ver como localizarlo.")

@using (@Html.BeginForm())
{
    @Html.EditorForModel()
    
    <input type="submit" value=@_("enviar") />
}

@_("Esto es una cadena"
+ " multilinea")

<input id="ScriptTest" type="button" value=@_("Prueba de Javascript") />

i18n.Sample/Views/Shared/_Layout.cshtml
@using i18n.Sample
@using System.Threading
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
	@*<link href="@Url.Content("~/Content/font-awesome.css")" rel="stylesheet" type="text/css" />*@
	<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/modernizr")
    <script src="@Url.Content("~/Scripts/jquery-1.8.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")" type="text/javascript"></script>
	<script src="@Url.Action("Index", "Localization", new { lang = Thread.CurrentThread.CurrentCulture.IetfLanguageTag, includes = "LocalizationDemo.js" })" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/i18n.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/LocalizationDemo.js")" type="text/javascript"></script>
</head>
<body>
    <div id="alerts" class="container">@Html.AlertSummary()</div>
	<div id="main" class="container" style="min-height: 450px">
		<div id="page-body" class="row">
			@RenderBody()
		</div>
	</div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>